### ISSUE TITLE
F12水波纹花屏以及dashboard颜色过渡不平滑怎么解决

### ISSUE THREAD

**Issue by lohcve** [liuyishengalan/Clover-for-ThinkPad-T470p#1]

**Comment by liuyishengalan** [comment]
是edid问题吗

**Comment by lohcve** [comment]
不是edid的问题，感觉是显卡硬件加速的问题，不知道你电脑是什么情况，有没有这个问题
![qq 20181106133540](https://user-images.githubusercontent.com/11513155/48044831-dcdd4e80-e1c8-11e8-8559-bd787f2f5e6a.jpg)

**Comment by lohcve** [comment]
仿冒1916可以解决这个问题
